# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

## Use patched devtools
r_github_packages:
  - hadley/devtools

after_success:
  - Rscript -e 'covr::codecov()'
